jobs:
- job: LintCode
  displayName: Lint code
  steps:
    - script: |
        az bicep build --file WeightLiftingTracker-API\WeightLiftingTrackerAPI\IaCTemplates\WebApp\main.bicep
      name: LintBicepCode
      displayName: Run Bicep linter