stages:

- stage: Test
  jobs:
  - job: RunTests

    steps:
      - task: DotNetCoreCLI@2
        displayName: Unit Tests
        inputs:
          command: 'test'
          projects: '**/TrackerAPI.Test/*.csproj'
      
      # - task: DotNetCoreCLI@2
      #   displayName: Specflow Tests
      #   inputs:
      #     command: 'test'
      #     projects: '**/API.SpecflowTests/*.csproj' 